from dataclasses import dataclass
import os
from dotenv import load_dotenv

load_dotenv()

def _ints(name: str) -> frozenset[int]:
    return frozenset(int(x.strip()) for x in os.getenv(name, "").split(",") if x.strip())

@dataclass(frozen=True)
class Settings:
    bot_token: str = os.getenv("BOT_TOKEN", "")
    openrouter_base_url: str = os.getenv("OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1").rstrip("/")
    openrouter_api_key: str = os.getenv("OPENROUTER_API_KEY", "")
    openrouter_model: str = os.getenv("OPENROUTER_MODEL", "thinkingmachines/inkling:free")
    openrouter_timeout: int = int(os.getenv("OPENROUTER_TIMEOUT", "240"))
    openrouter_site_url: str = os.getenv("OPENROUTER_SITE_URL", "")
    admin_ids: frozenset[int] = _ints("ADMIN_TELEGRAM_IDS")
    ollama_base_url: str = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434").rstrip("/")
    ollama_api_key: str = os.getenv("OLLAMA_API_KEY", "")
    ollama_model: str = os.getenv("OLLAMA_MODEL", "minimax-m3:cloud")
    agnes_base_url: str = os.getenv("AGNES_BASE_URL", "http://127.0.0.1:8765").rstrip("/")
    agnes_start_command: str = os.getenv("AGNES_START_COMMAND", "npx free-short-video --no-open")
    agnes_project_dir: str = os.getenv("AGNES_PROJECT_DIR", "")
    agnes_auto_start: bool = os.getenv("AGNES_AUTO_START", "true").lower() in {"1", "true", "yes", "on"}
    agnes_poll_seconds: int = int(os.getenv("AGNES_POLL_SECONDS", "10"))
    agnes_task_timeout: int = int(os.getenv("AGNES_TASK_TIMEOUT", "3600"))
    agnes_download_timeout: int = int(os.getenv("AGNES_DOWNLOAD_TIMEOUT", "120"))
    agnes_download_retries: int = int(os.getenv("AGNES_DOWNLOAD_RETRIES", "12"))
    agnes_status_timeout: int = int(os.getenv("AGNES_STATUS_TIMEOUT", "90"))
    telegram_video_max_mb: int = int(os.getenv("TELEGRAM_VIDEO_MAX_MB", "49"))
    telegram_retry_seconds: int = int(os.getenv("TELEGRAM_RETRY_SECONDS", "15"))
    whisper_base_url: str = os.getenv("WHISPER_BASE_URL", "http://127.0.0.1:8766").rstrip("/")
    whisper_model: str = os.getenv("WHISPER_MODEL", "small")
    whisper_timeout: int = int(os.getenv("WHISPER_TIMEOUT", "600"))
    max_voice_seconds: int = int(os.getenv("MAX_VOICE_SECONDS", "180"))
    whisper_min_confidence: float = float(os.getenv("WHISPER_MIN_CONFIDENCE", "0.55"))
    fish_audio_base_url: str = os.getenv("FISH_AUDIO_BASE_URL", "https://api.fish.audio").rstrip("/")
    fish_audio_api_key: str = os.getenv("FISH_AUDIO_API_KEY", "")
    fish_audio_reference_id: str = os.getenv("FISH_AUDIO_REFERENCE_ID", "")
    fish_voice_popular: str = os.getenv("FISH_VOICE_POPULAR", "")
    fish_voice_male: str = os.getenv("FISH_VOICE_MALE", "")
    fish_voice_female: str = os.getenv("FISH_VOICE_FEMALE", "")
    fish_voice_sports_energy: str = os.getenv("FISH_VOICE_SPORTS_ENERGY", "")
    fish_voice_sports_calm: str = os.getenv("FISH_VOICE_SPORTS_CALM", "")
    fish_voice_deep: str = os.getenv("FISH_VOICE_DEEP", "")
    fish_voice_youth: str = os.getenv("FISH_VOICE_YOUTH", "")
    fish_voice_soft_female: str = os.getenv("FISH_VOICE_SOFT_FEMALE", "")
    fish_voice_ar: str = os.getenv("FISH_VOICE_AR", "")
    fish_voice_fr: str = os.getenv("FISH_VOICE_FR", "")
    fish_voice_en: str = os.getenv("FISH_VOICE_EN", "")
    fish_voice_news_ar: str = os.getenv("FISH_VOICE_NEWS_AR", "")
    fish_voice_news_fr: str = os.getenv("FISH_VOICE_NEWS_FR", "")
    fish_voice_news_en: str = os.getenv("FISH_VOICE_NEWS_EN", "")
    fish_voice_documentary_ar: str = os.getenv("FISH_VOICE_DOCUMENTARY_AR", "")
    fish_voice_documentary_fr: str = os.getenv("FISH_VOICE_DOCUMENTARY_FR", "")
    fish_voice_documentary_en: str = os.getenv("FISH_VOICE_DOCUMENTARY_EN", "")
    fish_voice_storyteller_ar: str = os.getenv("FISH_VOICE_STORYTELLER_AR", "")
    fish_voice_storyteller_fr: str = os.getenv("FISH_VOICE_STORYTELLER_FR", "")
    fish_voice_storyteller_en: str = os.getenv("FISH_VOICE_STORYTELLER_EN", "")
    fish_voice_anime_storyteller_ar: str = os.getenv("FISH_VOICE_ANIME_STORYTELLER_AR", "")
    fish_voice_anime_storyteller_fr: str = os.getenv("FISH_VOICE_ANIME_STORYTELLER_FR", "")
    fish_voice_anime_storyteller_en: str = os.getenv("FISH_VOICE_ANIME_STORYTELLER_EN", "")
    fish_audio_model: str = os.getenv("FISH_AUDIO_MODEL", "s2.1-pro")
    fish_audio_fallback_model: str = os.getenv("FISH_AUDIO_FALLBACK_MODEL", "s2.1-pro-free")
    fish_audio_timeout: int = int(os.getenv("FISH_AUDIO_TIMEOUT", "180"))
    fish_audio_max_chars: int = int(os.getenv("FISH_AUDIO_MAX_CHARS", "3000"))
    fish_audio_latency: str = os.getenv("FISH_AUDIO_LATENCY", "balanced")
    fish_audio_chunk_length: int = int(os.getenv("FISH_AUDIO_CHUNK_LENGTH", "120"))
    free_daily_limit: int = int(os.getenv("FREE_DAILY_LIMIT", "100"))
    pro_daily_limit: int = int(os.getenv("PRO_DAILY_LIMIT", "300"))
    vip_daily_limit: int = int(os.getenv("VIP_DAILY_LIMIT", "2000"))
    free_video_daily_limit: int = int(os.getenv("FREE_VIDEO_DAILY_LIMIT", "20"))
    pro_video_daily_limit: int = int(os.getenv("PRO_VIDEO_DAILY_LIMIT", "60"))
    vip_video_daily_limit: int = int(os.getenv("VIP_VIDEO_DAILY_LIMIT", "200"))
    free_image_daily_limit: int = int(os.getenv("FREE_IMAGE_DAILY_LIMIT", "20"))
    pro_image_daily_limit: int = int(os.getenv("PRO_IMAGE_DAILY_LIMIT", "250"))
    vip_image_daily_limit: int = int(os.getenv("VIP_IMAGE_DAILY_LIMIT", "1000"))
    referral_inviter_bonus: int = int(os.getenv("REFERRAL_INVITER_IMAGE_BONUS", "5"))
    referral_new_user_bonus: int = int(os.getenv("REFERRAL_NEW_USER_IMAGE_BONUS", "2"))
    pro_price_stars: int = int(os.getenv("PRO_PRICE_STARS", "500"))
    vip_price_stars: int = int(os.getenv("VIP_PRICE_STARS", "1000"))
    subscription_days: int = int(os.getenv("SUBSCRIPTION_DAYS", "30"))
    dashboard_host: str = os.getenv("DASHBOARD_HOST", "127.0.0.1")
    dashboard_port: int = int(os.getenv("DASHBOARD_PORT", "8080"))
    dashboard_user: str = os.getenv("DASHBOARD_USER", "admin")
    dashboard_password: str = os.getenv("DASHBOARD_PASSWORD", "")
    phone_hash_secret: str = os.getenv("PHONE_HASH_SECRET", "")
    session_ttl_minutes: int = int(os.getenv("SESSION_TTL_MINUTES", "60"))
    max_context_messages: int = int(os.getenv("MAX_CONTEXT_MESSAGES", "20"))
    rate_limit_per_minute: int = int(os.getenv("RATE_LIMIT_PER_MINUTE", "8"))
    creator_max_duration: int = int(os.getenv("CREATOR_MAX_DURATION", "60"))
    creator_max_scenes: int = int(os.getenv("CREATOR_MAX_SCENES", "12"))
    creator_music_volume: float = float(os.getenv("CREATOR_MUSIC_VOLUME", "0.14"))
    creator_music_dir: str = os.getenv("CREATOR_MUSIC_DIR", "assets/music")
    creator_video_encoder: str = os.getenv("CREATOR_VIDEO_ENCODER", "auto").lower()
    creator_image_parallelism: int = int(os.getenv("CREATOR_IMAGE_PARALLELISM", "3"))
    creator_default_mode: str = os.getenv("CREATOR_DEFAULT_MODE", "balanced").lower()
    agnes_animation_concurrency: int = int(os.getenv("AGNES_ANIMATION_CONCURRENCY", "2"))
    creator_scene_animation_timeout: int = int(os.getenv("CREATOR_SCENE_ANIMATION_TIMEOUT", "1200"))
    creator_clip_cache_seconds: int = int(os.getenv("CREATOR_CLIP_CACHE_SECONDS", "3600"))
    caption_font_name: str = os.getenv("CAPTION_FONT_NAME", "Tahoma")
    caption_font_file: str = os.getenv("CAPTION_FONT_FILE", "")
    caption_primary_color: str = os.getenv("CAPTION_PRIMARY_COLOR", "&H00FFFFFF")
    caption_highlight_color: str = os.getenv("CAPTION_HIGHLIGHT_COLOR", "&H0000D7FF")
    creator_concurrency: int = int(os.getenv("CREATOR_CONCURRENCY", "1"))
    image_concurrency: int = int(os.getenv("IMAGE_CONCURRENCY", "2"))
    tts_concurrency: int = int(os.getenv("TTS_CONCURRENCY", "2"))
    music_concurrency: int = int(os.getenv("MUSIC_CONCURRENCY", "1"))
    upload_concurrency: int = int(os.getenv("UPLOAD_CONCURRENCY", "2"))
    telegram_upload_timeout: int = int(os.getenv("TELEGRAM_UPLOAD_TIMEOUT", "900"))
    delivery_retention_seconds: int = int(os.getenv("DELIVERY_RETENTION_SECONDS", "3600"))
    delivery_retry_seconds: int = int(os.getenv("DELIVERY_RETRY_SECONDS", "60"))
    output_dir: str = os.getenv("OUTPUT_DIR", "data/outputs")
    hide_service_windows: bool = os.getenv("HIDE_SERVICE_WINDOWS", "true").lower() in {"1","true","yes","on"}
    puter_enabled: bool = os.getenv("PUTER_ENABLED", "false").lower() in {"1","true","yes","on"}
    puter_mode: str = os.getenv("PUTER_MODE", "fallback").lower()
    puter_base_url: str = os.getenv("PUTER_BASE_URL", "http://127.0.0.1:8770").rstrip("/")
    puter_model: str = os.getenv("PUTER_MODEL", "gpt-5.4-nano")
    puter_timeout: int = int(os.getenv("PUTER_TIMEOUT", "180"))
    music_max_duration: int = int(os.getenv("MUSIC_MAX_DURATION", "900"))
    music_max_mb: int = int(os.getenv("MUSIC_MAX_MB", "45"))
    database_path: str = os.getenv("DATABASE_PATH", "elden_ai.db")
    log_level: str = os.getenv("LOG_LEVEL", "INFO").upper()

    def validate(self) -> None:
        missing = []
        if not self.bot_token or self.bot_token.startswith("PASTE_"): missing.append("BOT_TOKEN")
        if not self.dashboard_password or self.dashboard_password.startswith("CHANGE_"): missing.append("DASHBOARD_PASSWORD")
        if missing: raise RuntimeError("Missing secure configuration: " + ", ".join(missing))

settings = Settings()
settings.validate()
